### ISSUE TITLE
reput: 2.5.0.27

### ISSUE THREAD

**Issue by notDavid** [FiloSottile/mostly-harmless#6]
Hi there, i was wondering if you have used reput on version 2.5.0.27?

Also, in the description i read:

> reput will automatically patch xochitl to keep the Web UI from turning off at each reboot, and to bind it to the loopback interface, as usb0 isn't configured with an IP at boot.

Does that mean the web interface will be available over Wifi even when the USB cable is not attached?

Thank you :)

**Comment by danshick** [comment]
https://github.com/nickmooney/remarkable-patches/tree/master/2.5.0.27
